import React, { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Camera, Users, Globe, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { LiveStream } from "@/entities/LiveStream";
import { User } from "@/entities/User";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";

export default function GoLiveModal({ open, onOpenChange, onStreamCreated }) {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    title: "",
    description: "",
    category: "",
    isPublic: true
  });
  const [loading, setLoading] = useState(false);

  const categories = [
    { value: "majlis", label: "🎤 Majlis" },
    { value: "quran", label: "📖 Quran Recitation" },
    { value: "lecture", label: "📚 Islamic Lecture" },
    { value: "dua", label: "🤲 Dua & Zikr" },
    { value: "talk", label: "💬 Community Talk" },
    { value: "other", label: "📺 Other" }
  ];

  const handleStartLive = async () => {
    setLoading(true);
    try {
      const user = await User.me();
      
      const streamData = {
        title: formData.title,
        description: formData.description,
        category: formData.category,
        host_id: user.id,
        host_name: user.full_name,
        host_image: user.profile_image || `https://ui-avatars.com/api/?name=${encodeURIComponent(user.full_name)}&background=059669&color=fff`,
        is_public: formData.isPublic,
        status: "live",
        viewer_count: 0,
        total_views: 0,
        started_at: new Date().toISOString(),
        tags: [formData.category, "Live"],
        // Simulated stream URL - in production, this would be generated by streaming service
        stream_url: `https://stream.zahoor.app/live/${Date.now()}`,
      };

      const newStream = await LiveStream.create(streamData);
      
      toast.success("🔴 You're Live!", {
        description: "Your stream is now broadcasting to the community.",
      });
      
      onOpenChange(false);
      
      // Navigate to the watch page for this stream
      setTimeout(() => {
        navigate(createPageUrl(`WatchStream?id=${newStream.id}`));
      }, 500);
      
      if (onStreamCreated) {
        onStreamCreated();
      }
    } catch (error) {
      console.error("Error starting stream:", error);
      toast.error("Failed to start stream", {
        description: "Please try again or check your connection.",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md bg-white border-emerald-200">
        <DialogHeader>
          <DialogTitle className="text-emerald-800 flex items-center gap-2">
            <Camera className="w-5 h-5 text-red-600" />
            Go Live
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div>
            <Label htmlFor="title" className="text-emerald-700">Event Title *</Label>
            <Input
              id="title"
              placeholder="e.g., Evening Majlis - Imam Hussain (a.s.)"
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              className="border-emerald-200 focus:border-emerald-500"
            />
          </div>

          <div>
            <Label htmlFor="description" className="text-emerald-700">Description</Label>
            <Textarea
              id="description"
              placeholder="Brief description of your live stream..."
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              className="border-emerald-200 focus:border-emerald-500 min-h-20"
            />
          </div>

          <div>
            <Label htmlFor="category" className="text-emerald-700">Category *</Label>
            <Select value={formData.category} onValueChange={(value) => setFormData({ ...formData, category: value })}>
              <SelectTrigger className="border-emerald-200">
                <SelectValue placeholder="Select stream category" />
              </SelectTrigger>
              <SelectContent>
                {categories.map((cat) => (
                  <SelectItem key={cat.value} value={cat.value}>
                    {cat.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex items-center justify-between p-3 bg-emerald-50 rounded-lg">
            <div className="flex items-center gap-2">
              {formData.isPublic ? (
                <Globe className="w-4 h-4 text-emerald-600" />
              ) : (
                <Users className="w-4 h-4 text-emerald-600" />
              )}
              <div>
                <p className="text-sm font-medium text-emerald-800">
                  {formData.isPublic ? "Public Stream" : "Followers Only"}
                </p>
                <p className="text-xs text-emerald-600">
                  {formData.isPublic ? "Anyone can watch" : "Only your followers can watch"}
                </p>
              </div>
            </div>
            <Switch
              checked={formData.isPublic}
              onCheckedChange={(checked) => setFormData({ ...formData, isPublic: checked })}
            />
          </div>
        </div>

        <div className="flex gap-3">
          <Button 
            variant="outline" 
            onClick={() => onOpenChange(false)}
            className="flex-1 border-emerald-300 text-emerald-700"
          >
            Cancel
          </Button>
          <Button 
            onClick={handleStartLive}
            disabled={!formData.title || !formData.category || loading}
            className="flex-1 bg-gradient-to-r from-red-500 to-red-600 hover:from-red-600 hover:to-red-700 text-white"
          >
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Starting...
              </>
            ) : (
              <>🔴 Start Live</>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}